export enum AppointmentStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  IN_SERVICE = 'IN_SERVICE',
  SERVICE_COMPLETED = 'SERVICE_COMPLETED',
  COMPLETED = 'COMPLETED',

  CANCELLED = 'CANCELLED',
}
